
title: coffeestain.io
email: pc@coffeestain.io
logo: "assets/images/coffee-long.png"
description: >- # this means to ignore newlines until "baseurl:"
  Software Quality Assurance jobs simplified, curated and updated. 
  We are engineers, we understand the market. We have experience, we understand 
  your company needs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://coffeestain.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  coffeestain.io

# Build settings
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - index.markdown
  - freelancer.markdown
  - companies.markdown
  - about.markdown

google_analytics: UA-139143178-5
